# Uncomment the next line to define a global platform for your project
platform :ios, '14.4'

target 'SavePets' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SavePets
  pod 'BSImagePicker', '~> 3.1'
  pod 'Presentr'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire', '~> 5.2'

  target 'SavePetsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SavePetsUITests' do
    # Pods for testing
  end

end
